/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.8/userguide/building_java_projects.html in the Gradle documentation.
 */

val minecraft_version = project.findProperty("minecraft.version") as String
val forge_version = project.findProperty("forge.version") as String
val forge_gradle_version = project.findProperty("forge.gradle_version") as String

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    id("net.minecraftforge.gradle") version "[6.0.35,6.2)"
    id("java")
}
apply(plugin = "net.minecraftforge.gradle")

repositories {
    // Use Maven Central for resolving dependencies.
   maven {
      name = "Forge"
      url = uri("https://files.minecraftforge.net/maven")
   }
   gradlePluginPortal()
   mavenCentral()
}

dependencies {
    // This dependency is used by the application.
   implementation(libs.guava)
   implementation("net.minecraftforge.gradle:ForgeGradle:$forge_gradle_version")
   "minecraft"("net.minecraftforge:forge:$minecraft_version-$forge_version")
}

minecraft {
   mappings("official", "$minecraft_version")
   reobf = false
   copyIdeResources = true
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(project.findProperty("java_version") as String)
    }
}

application {
   mainClass = "main.java.umbra.forgebase.ForgeMain"
}


