/*
 * This source file was generated by the Gradle 'init' task
 */
package fabricbase;

import umbra.fabricbase.FabricMain;

class AppTest {
    public void appHasAGreeting() {
        @SuppressWarnings("unused")
        FabricMain classUnderTest = new FabricMain();
    }
}
