/*
 * This source file was generated by the Gradle 'init' task
 */
package paperbase;

import umbra.paperbase.PluginMain;

class AppTest {
    public void appHasAGreeting() {
        @SuppressWarnings("unused")
        PluginMain classUnderTest = new PluginMain();
    }
}
